### ISSUE TITLE
Container build fails with fedora 28 buildroot.

### ISSUE THREAD

**Issue by cverna** [projectatomic/atomic-reactor#1005]
When using a buildroot based on f28, the build failed [0] with the following error message

```Image build failed. Error in plugin docker_api: TypeError("build() got an unexpected keyword argument 'stream'",). OSBS build id: docker-f28-8da47-9```

It appears that the version of python-docker available in f28 (3.2.1-1.fc28) breaks the API used in atomic-reactor. For information the version of python-docker available in f27 is 2.6.1-1.fc27

For now I am making sure that the buildroot image is using a f27 base image. 

[0] - https://koji.fedoraproject.org/koji/taskinfo?taskID=27139627

**Comment by twaugh** [comment]
Looks like we need to try that call
- with both 'pull' and 'stream' keyword arguments
- with just 'stream' keyword argument
- without either

**Comment by cverna** [comment]
To do some testing, I remove the `stream` argument from https://github.com/projectatomic/atomic-reactor/blob/1.6.31/atomic_reactor/core.py#L342 and https://github.com/projectatomic/atomic-reactor/blob/1.6.31/atomic_reactor/core.py#L347 calls.

I know have a error in the docker-squash library

```2018-06-04 18:30:08,958 - atomic_reactor.plugin - DEBUG - running plugin 'squash'
2018-06-04 18:30:08,958 - atomic_reactor.plugin - INFO - running plugin instance with args: '{}'
2018-06-04 18:30:08,958 - atomic_reactor.plugins.squash - INFO - will squash from base-image: 'sha256:cc510acfcd701a409014118d5f417f0022520802a26c650866b8a9594d75f3a7'
2018-06-04 18:30:08,958 - atomic_reactor.plugins.squash - DEBUG - Preparing Docker client...
2018-06-04 18:30:08,963 - atomic_reactor.plugins.squash - DEBUG - Docker client ready
2018-06-04 18:30:08,965 - atomic_reactor.plugins.squash - INFO - docker-squash version 1.0.5, Docker 584d391/1.13.1, API 1.26...
2018-06-04 18:30:08,966 - atomic_reactor.plugins.squash - INFO - Using v2 image format
2018-06-04 18:30:08,966 - atomic_reactor.plugins.squash - DEBUG - Using /var/tmp/docker-squash-q4fCEH as the temporary directory
2018-06-04 18:30:08,984 - atomic_reactor.plugins.squash - INFO - Old image has 23 layers
2018-06-04 18:30:08,984 - atomic_reactor.plugins.squash - DEBUG - Old layers: [u'<missing>', u'<missing>', u'sha256:cc510acfcd701a409014118d5f417f0022520802a26c650866b8a9594d75f3a7', u'sha256:3bed7ce8e140590ebc49b9d2e5cde593508909f48d0c33742094eb3950c72cfd', u'sha256:a201871b9448175220cf8bf0b283ff8052795ac02fbd548de741fd02576e1807', u'sha256:c5323b01fa7eee40b0711bcddee35358915008732dfb54858e00744a0e27759a', u'sha256:60a529542b2bb273df3a4ec02fad805c160398861c044fd3cfb4220cf94ebfa5', u'sha256:1cf38ccf4984e296aee663b3d2b807a7ab09eb65b9ef925f6c3fd0d04c696af3', u'sha256:0321880451142ace34926b65670b9446bcb792b6704f3c91068a1e3ed219d51c', u'sha256:89d5f362038569a704eed7c112ab21af2b73d605e022385eac4cbc3d6435e688', u'sha256:df7dab5804816e347241e81fec3274309cccc251adf963688a3b4b430b68e76c', u'sha256:5ec773082c385b0f9f5d8bd71f2407b0988e365d3f2c4acfa2161e4ec6d56b92', u'sha256:bb30a01206823d669eb997902558f30056a7e233c17bfdcdbd4a408020dc09e6', u'sha256:1cc0a15f4233bb27014ff8dcdb6de7bfa7c376ab2e73f438728bcee97b647089', u'sha256:59f99b1c6a42fd74e86c75d86cb186acc5f99beef5af8e30654657ed571e6be2', u'sha256:f1bb0ebab8565833e2edabb8dd9bca7191d0b8280cee7ce3e484a0fbd0c713aa', u'sha256:714822298742e8248378e2157164a591789685089f83aeb63f42c723c86024d5', u'sha256:7257d2c22e6ac10800da80cf4e728c50d4f9924706884b90ecc5de8e5f6a017b', u'sha256:32e23a617c6d39f72ab08221ced24712e445111e726cb969300ea3ff04afaf44', u'sha256:e27ec5618b938b96ad270e28d863df2d600bffc90b0a8c9cdd3c4b6b0e289e91', u'sha256:76f4cf26915fc9f16ed369542a85d78bcee66f341e76a8498d97883e85f8e2c1', u'sha256:77cbb4867ba9123b5cab72a559751d16b824597a22f8f8076a11c983e471eae8', u'sha256:2f25f74f7d4f6377b18254c253ef16c78adbfe19c6bbb67f636f3f736c806fcd']
2018-06-04 18:30:08,984 - atomic_reactor.plugins.squash - DEBUG - We detected layer as the argument to squash
2018-06-04 18:30:08,987 - atomic_reactor.plugins.squash - DEBUG - Layer ID to squash from: sha256:cc510acfcd701a409014118d5f417f0022520802a26c650866b8a9594d75f3a7
2018-06-04 18:30:08,987 - atomic_reactor.plugins.squash - INFO - Checking if squashing is necessary...
2018-06-04 18:30:08,987 - atomic_reactor.plugins.squash - INFO - Attempting to squash last 20 layers...
2018-06-04 18:30:08,987 - atomic_reactor.plugins.squash - DEBUG - Layers to squash: [u'sha256:3bed7ce8e140590ebc49b9d2e5cde593508909f48d0c33742094eb3950c72cfd', u'sha256:a201871b9448175220cf8bf0b283ff8052795ac02fbd548de741fd02576e1807', u'sha256:c5323b01fa7eee40b0711bcddee35358915008732dfb54858e00744a0e27759a', u'sha256:60a529542b2bb273df3a4ec02fad805c160398861c044fd3cfb4220cf94ebfa5', u'sha256:1cf38ccf4984e296aee663b3d2b807a7ab09eb65b9ef925f6c3fd0d04c696af3', u'sha256:0321880451142ace34926b65670b9446bcb792b6704f3c91068a1e3ed219d51c', u'sha256:89d5f362038569a704eed7c112ab21af2b73d605e022385eac4cbc3d6435e688', u'sha256:df7dab5804816e347241e81fec3274309cccc251adf963688a3b4b430b68e76c', u'sha256:5ec773082c385b0f9f5d8bd71f2407b0988e365d3f2c4acfa2161e4ec6d56b92', u'sha256:bb30a01206823d669eb997902558f30056a7e233c17bfdcdbd4a408020dc09e6', u'sha256:1cc0a15f4233bb27014ff8dcdb6de7bfa7c376ab2e73f438728bcee97b647089', u'sha256:59f99b1c6a42fd74e86c75d86cb186acc5f99beef5af8e30654657ed571e6be2', u'sha256:f1bb0ebab8565833e2edabb8dd9bca7191d0b8280cee7ce3e484a0fbd0c713aa', u'sha256:714822298742e8248378e2157164a591789685089f83aeb63f42c723c86024d5', u'sha256:7257d2c22e6ac10800da80cf4e728c50d4f9924706884b90ecc5de8e5f6a017b', u'sha256:32e23a617c6d39f72ab08221ced24712e445111e726cb969300ea3ff04afaf44', u'sha256:e27ec5618b938b96ad270e28d863df2d600bffc90b0a8c9cdd3c4b6b0e289e91', u'sha256:76f4cf26915fc9f16ed369542a85d78bcee66f341e76a8498d97883e85f8e2c1', u'sha256:77cbb4867ba9123b5cab72a559751d16b824597a22f8f8076a11c983e471eae8', u'sha256:2f25f74f7d4f6377b18254c253ef16c78adbfe19c6bbb67f636f3f736c806fcd']
2018-06-04 18:30:08,987 - atomic_reactor.plugins.squash - DEBUG - Layers to move: [u'<missing>', u'<missing>', u'sha256:cc510acfcd701a409014118d5f417f0022520802a26c650866b8a9594d75f3a7']
2018-06-04 18:30:08,987 - atomic_reactor.plugins.squash - INFO - Saving image sha256:2f25f74f7d4f6377b18254c253ef16c78adbfe19c6bbb67f636f3f736c806fcd to /var/tmp/docker-squash-q4fCEH/old directory...
2018-06-04 18:30:08,987 - atomic_reactor.plugins.squash - DEBUG - Try #1...
2018-06-04 18:30:16,479 - atomic_reactor.plugins.squash - ERROR - 'generator' object has no attribute 'read'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/docker_squash/image.py", line 321, in _save_image
    with tarfile.open(fileobj=image, mode='r|') as tar:
  File "/usr/lib64/python2.7/tarfile.py", line 1705, in open
    t = cls(name, filemode, stream, **kwargs)
  File "/usr/lib64/python2.7/tarfile.py", line 1587, in __init__
    self.firstmember = self.next()
  File "/usr/lib64/python2.7/tarfile.py", line 2358, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python2.7/tarfile.py", line 1251, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib64/python2.7/tarfile.py", line 579, in read
    buf = self._read(size)
  File "/usr/lib64/python2.7/tarfile.py", line 587, in _read
    return self.__read(size)
  File "/usr/lib64/python2.7/tarfile.py", line 612, in __read
    buf = self.fileobj.read(self.bufsize)
AttributeError: 'generator' object has no attribute 'read'```

**Comment by cverna** [comment]
A new docker API call in https://github.com/projectatomic/atomic-reactor/blob/master/atomic_reactor/core.py#L326 is needed. This call will not have the `pull` and `stream` attributes.

I guess we this call should be tried last if the 2 previous call are failing.

**Comment by twaugh** [comment]
Yes, that sounds like the right approach.
