### ISSUE TITLE
Error attempting tito build in mock

### ISSUE THREAD

**Issue by maxamillion** [projectatomic/atomic-reactor#250]
Performing a build with tito fails in mock `tito build --rpm --test --builder mock --arg mock=epel-7-x86_64  `

The mock logs are:

```
RPM build errors:
error: File not found by glob: /builddir/build/BUILDROOT/atomic-reactor-1.4.0-2.git.0.cf8b96c.el7.centos.x86_64/usr/lib/python2.7/site-packages/atomic_reactor/plugins/post_store_metadata_in_osv3.py*
    File not found by glob: /builddir/build/BUILDROOT/atomic-reactor-1.4.0-2.git.0.cf8b96c.el7.centos.x86_64/usr/lib/python2.7/site-packages/atomic_reactor/plugins/post_store_metadata_in_osv3.py*
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/atomic-reactor.spec 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/util.py", line 494, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/atomic-reactor.spec 
LEAVE do --> EXCEPTION RAISED
```

**Comment by maxamillion** [comment]
https://github.com/projectatomic/atomic-reactor/pull/251
