### ISSUE TITLE
Plugin failure should fail the whole build

### ISSUE THREAD

**Issue by bkabrda** [projectatomic/atomic-reactor#261]
Plugins should fail the build and should "fail fast". If atomic-reactor can't import a plugin that user requested via `build.json` or that plugin fails, then the whole build should fail. I also think it should fail immediately, except perhaps exit plugins that get run either way.
The dangers of current behavior include
- delivering a different result that user wanted
- user not noticing that he got a different result, since atomic-reactor logs are pretty verbose and hard to read
Let's discuss :) @TomasTomecek @twaugh @mmilata @jpopelka

**Comment by pbabinca** [comment]
We had seen the issue which caused build to stuck in running state just because the failure of post_cp_build_image_to_nfs plugin wasn't detected:

```
2015-08-07 07:40:06,179 - atomic_reactor.plugins.cp_built_image_to_nfs - DEBUG - mount NFS u'builder.example.com:/mnt/registry/image-export' at /atomic-reactor-nfs-mountpoint/
mount.nfs: Connection timed out
2015-08-07 07:42:19,184 - atomic_reactor.plugin - WARNING - plugin 'cp_built_image_to_nfs' raised an exception: 'CalledProcessError()'
2015-08-07 07:42:19,203 - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugin.py", line 180, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_cp_built_image_to_nfs.py", line 106, in run
    self.mount_nfs()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_cp_built_image_to_nfs.py", line 98, in mount_nfs
    mount(self.nfs_server_path, self.mountpoint)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_cp_built_image_to_nfs.py", line 47, in mount
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '[u'mount', u'-t', u'nfs', u'-o', u'nolock', u'builder.example.com:/mnt/registry/image-export', u'/atomic-reactor-nfs-mountpoint/']' returned non-zero exit status 32
2015-08-07 07:42:19,203 - atomic_reactor.plugin - DEBUG - running plugin 'tag_by_labels'
```
And the build log continues as the build still appeared to be running.

The original problem for plugin failure was the nfs server not running.

**Comment by pbabinca** [comment]
I've seen the same problem this time on different plugin:
```
2015-08-10 10:39:37,157 - atomic_reactor.plugin - WARNING - plugin 'pulp_push' raised an exception: 'DockPulpError(u'Timed out waiting for task a114f
d9c-efa1-4222-aee7-3fe8f02dd032',)'
2015-08-10 10:39:37,234 - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugin.py", line 180, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py", line 210, in run
    crane_repos = self.push_tar(image_stream, image_names)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py", line 199, in push_tar
    return uploader.push_tarball_to_pulp(image_names)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py", line 115, in push_tarball_to_pu
lp
    task_ids = p.push_tar_to_pulp(repos_tags_mapping, self.filename)
  File "build/bdist.linux-x86_64/egg/dockpulp/__init__.py", line 630, in push_tar_to_pulp
    self.upload(tarfile)
  File "build/bdist.linux-x86_64/egg/dockpulp/__init__.py", line 775, in upload
    self.watch(tid, timeout=timer)  # whichever is greater
  File "build/bdist.linux-x86_64/egg/dockpulp/__init__.py", line 796, in watch
    raise errors.DockPulpError('Timed out waiting for task %s' % tid)
DockPulpError: Timed out waiting for task a114fd9c-efa1-4222-aee7-3fe8f02dd032

2015-08-10 10:39:37,235 - atomic_reactor.plugin - DEBUG - running plugin 'all_rpm_packages'
```

The original problem for that pulp timeout was restart of the pulp resource manager which was broken too.

**Comment by TomasTomecek** [comment]
I agree we should take care of this. It's pretty annoying that some plugins are not run and one figures out only when checking logs. Also slightly related: https://github.com/projectatomic/atomic-reactor/issues/92
