### ISSUE TITLE
plugin 'bump_release' raised an exception: 'AttributeError("can't set attribute",)'

### ISSUE THREAD

**Issue by jpopelka** [projectatomic/atomic-reactor#285]
Steps to reproduce:
$ dnf install python-pygit2
$  py.test -vv -x tests/plugins/test_bump_release.py

```
atomic_reactor.plugin - DEBUG - running plugin 'bump_release'
atomic_reactor.plugin - INFO - running plugin instance with args: '{u'author_email': u'root@example.com', u'git_ref': '84be20b445b9cebddc0890bdff431587815d3efc', u'author_name': u'OSBS Build System', u'push_url': u'/', u'commit_message': u'foo'}'
atomic_reactor.plugins.bump_release - INFO - Incrementing release label
atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/home/jpopelka/git/atomic-reactor/atomic_reactor/plugin.py", line 203, in run
    plugin_response = plugin_instance.run()
  File "/home/jpopelka/git/atomic-reactor/atomic_reactor/plugins/pre_bump_release.py", line 260, in run
    self.bump(repo, branch)
  File "/home/jpopelka/git/atomic-reactor/atomic_reactor/plugins/pre_bump_release.py", line 169, in bump
    remote.push_url = self.push_url
AttributeError: can't set attribute
```

**Comment by twaugh** [comment]
What version of python-pygit2 is that?

**Comment by jpopelka** [comment]
`python-pygit2-0.23.0-0.1.fc23.x86_64`
`libgit2-0.23.0-1.fc23.1.x86_64`

I tried to downgrade `python-pygit2` to `0.22.1` and `libgit2` to `0.22.3/0.22.2/0.22.1`, but then there's other error directly in `pygit2`, so I can't test it.

**Comment by twaugh** [comment]
OK, there's an accessor function for it now.

**Comment by twaugh** [comment]
... but there's no backwards compability, nice.
