### ISSUE TITLE
support basic auth in store_metadata_in_osv3 plugin

### ISSUE THREAD

**Issue by maxamillion** [projectatomic/atomic-reactor#294]
I'm not entirely sure if this is a bug or a configuration issue but I can't for the life of me figure it out and I've dug through enough of the osbs-client and atomic-reactor code to realize that I'm at a point that I need to ask for help.

```
2015-09-01 02:17:20,687 - atomic_reactor.plugins.store_metadata_in_osv3 - INFO - build id = atomic-reactor-dockerfile-test-20150831-210358
2015-09-01 02:17:20,835 - osbs.core - ERROR - [401] 'Location' header is missing in response, cannot retrieve token
2015-09-01 02:17:20,861 - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.4.0-py2.7.egg/atomic_reactor/plugin.py", line 203, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.4.0-py2.7.egg/atomic_reactor/plugins/exit_store_metadata_in_osv3.py", line 128, in run
    osbs.set_annotations_on_build(build_id, labels, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 39, in catch_exceptions
    raise OsbsException(cause=ex, traceback=sys.exc_info()[2])
OsbsException: ValueError(u'Token was not retrieved successfully.',)

Original traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 28, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 315, in set_annotations_on_build
    return self.os.set_annotations_on_build(build_id, annotations, namespace=namespace)
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 328, in set_annotations_on_build
    build_json = self._get(url).json()
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 85, in _get
    headers, kwargs = self._request_args(with_auth, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 77, in _request_args
    raise ValueError("Token was not retrieved successfully.")
ValueError(u'Token was not retrieved successfully.',)
```

I am starting this build with osbs and I'm able to get a token with osbs
```
$ osbs get-token
2015-08-31 21:27:09,948 - osbs.core - INFO - using basic authentication
xoWlj_PLH7PWFTHZDmirDo-bvF-ILMPQx6o9LWh7-dA
```

However, running the build from atomic-reactor at the command line outside of osbs also causes this issue.

**Comment by maxamillion** [comment]
Also, here's verbose output from osbs if that's helpful. (This is a VM on my laptop behind a NAT so I'm not overly concerned with tokens in the comments here)

```
# osbs --verbose get-token
2015-08-31 21:38:40,337 - osbs - DEBUG - Logging level set to debug
2015-08-31 21:38:40,338 - osbs.core - INFO - using basic authentication
* About to connect() to losbs.example.com port 8443 (#0)
*   Trying 192.168.122.28... * connected
* Connected to losbs.example.com (192.168.122.28) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_RSA_WITH_AES_256_CBC_SHA
* Server certificate:
*       subject: CN=losbs.example.com
*       start date: Aug 27 15:17:28 2015 GMT
*       expire date: Aug 26 15:17:29 2016 GMT
*       common name: losbs.example.com
*       issuer: CN=openshift-signer@1440688648
* Server auth using Basic with user 'builder'
> GET /oauth/authorize?response_type=token&client_id=openshift-challenging-client HTTP/1.1
Authorization: Basic YnVpbGRlcjpidWlsZGVy
User-Agent: PycURL/7.19.7
Host: losbs.example.com:8443
Accept: */*

< HTTP/1.1 302 Found
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Expires: Fri, 01 Jan 1990 00:00:00 GMT
< Location: https://losbs.example.com:8443/oauth/token/implicit#access_token=YVjqHBLhb_JbmJyxsrt04clFzf0kXWDIda-cLA_RZuY&expires_in=86400&token_type=Bearer
< Pragma: no-cache
* Added cookie ssn="MTQ0MTA3NTEyNHx2SW8zdjVoVzVDVWt5X3pTTkR6a1BLZUdYcGNHcDhWNE53QXVPYmxBVVFKZ09weV9qVjV3TFE2b25QcW0zeXZfYy1hRnRuemJ2VHN1LWdNV29xdkh3aXlRdkY4OUF1MkNFUmhEMEdCZXNRZ0I0ODgwN19sRVZHNnF4Mmk3dm55RTV3PT18o1r70X4gSkzQL7RxiE2CDQFijqFp1X03L-MsP57PJjQ=" for domain losbs.example.com, path /, expire 1441078720
< Set-Cookie: ssn=MTQ0MTA3NTEyNHx2SW8zdjVoVzVDVWt5X3pTTkR6a1BLZUdYcGNHcDhWNE53QXVPYmxBVVFKZ09weV9qVjV3TFE2b25QcW0zeXZfYy1hRnRuemJ2VHN1LWdNV29xdkh3aXlRdkY4OUF1MkNFUmhEMEdCZXNRZ0I0ODgwN19sRVZHNnF4Mmk3dm55RTV3PT18o1r70X4gSkzQL7RxiE2CDQFijqFp1X03L-MsP57PJjQ=; Path=/; Expires=Tue, 01 Sep 2015 03:38:44 UTC; Max-Age=3600; HttpOnly; Secure
< Date: Tue, 01 Sep 2015 02:38:44 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host losbs.example.com left intact
* Closing connection #0
2015-08-31 21:38:40,420 - osbs.http - DEBUG - raw headers: u'HTTP/1.1 302 Found\r\nCache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nExpires: Fri, 01 Jan 1990 00:00:00 GMT\r\nLocation: https://losbs.example.com:8443/oauth/token/implicit#access_token=YVjqHBLhb_JbmJyxsrt04clFzf0kXWDIda-cLA_RZuY&expires_in=86400&token_type=Bearer\r\nPragma: no-cache\r\nSet-Cookie: ssn=MTQ0MTA3NTEyNHx2SW8zdjVoVzVDVWt5X3pTTkR6a1BLZUdYcGNHcDhWNE53QXVPYmxBVVFKZ09weV9qVjV3TFE2b25QcW0zeXZfYy1hRnRuemJ2VHN1LWdNV29xdkh3aXlRdkY4OUF1MkNFUmhEMEdCZXNRZ0I0ODgwN19sRVZHNnF4Mmk3dm55RTV3PT18o1r70X4gSkzQL7RxiE2CDQFijqFp1X03L-MsP57PJjQ=; Path=/; Expires=Tue, 01 Sep 2015 03:38:44 UTC; Max-Age=3600; HttpOnly; Secure\r\nDate: Tue, 01 Sep 2015 02:38:44 GMT\r\nContent-Length: 0\r\nContent-Type: text/plain; charset=utf-8'
2015-08-31 21:38:40,421 - osbs.core - DEBUG - fragment is 'access_token=YVjqHBLhb_JbmJyxsrt04clFzf0kXWDIda-cLA_RZuY&expires_in=86400&token_type=Bearer'
YVjqHBLhb_JbmJyxsrt04clFzf0kXWDIda-cLA_RZuY
```

**Comment by twaugh** [comment]
Do you have `use_auth` set in `osbs.conf`?

**Comment by TomasTomecek** [comment]
Looks like that you are using username/password based authentication. Unfortunately, we don't support that in the plugin atm, will fix.

**Comment by TomasTomecek** [comment]
we'll also need to enable this in osbs-client

**Comment by mmilata** [comment]
@maxamillion I'm assuming you're running openshift origin/enterprise with default authentication options, i.e. with the `AllowAllPasswordIdentityProvider` authentication provider, without authenticating proxy in front of the instance.

I'd prefer if we didn't pass the username/password to atomic-reactor - it will get stored in the build logs and build metadata (iirc). I'd suggest two alternatives instead:

* For development purposes you can bypass authentication entirely. You can do this by using `use_auth=false` in osbs.conf. You'll have to set openshift to allow unauthenticated users to start build by running `oadm policy add-role-to-group edit system:unauthenticated`.

* In production we use authenticating proxy combined with the `RequestHeaderIdentityProvider`. The proxy takes care of the authentication and if it succeeds it sets the `X-Remote-User` http header which openshift uses as the user's identity. The proxy is configured so that whenever request comes from internal docker IP range (i.e. from atomic reactor) it sends the header without authentication. The configuration is a bit complicated, I can provide details if you want to set it up.

**Comment by maxamillion** [comment]
@twaugh - I do yes.

@TomasTomecek - Alright, thanks.

@mmilata - That's exactly it, I'm running Origin with default authentication options set. I thought I'd already set `oadm policy add-role-to-group edit system:unauthenticated` and had some issues which is why I set `use_auth=true` to begin with but I'll double check and make sure. It's entirely possible that I missed something. Thank you for your feedback and recommendations for dev vs prod use cases.

**Comment by maxamillion** [comment]
For the sake of posterity, I wanted to write this here. I spoke with @mmilata on IRC and we were able to determine that the issue is because I am using an older version of osbs which is currently packaged in EPEL (`osbs-0.14-1.el6.noarch`) I need the option `metadata_plugin_use_auth=false` added to my `/etc/osbs.conf` along with the `use_auth=false` but that won't be the case in the future or if I was using an install from git.

**Comment by maxamillion** [comment]
This has been resolved, I'm marking it as closed. Thanks to everyone who commented.
