### ISSUE TITLE
bump_release: commit IDs and branch names are mixed

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#343]
```
2015-10-07 04:56:02,768 - atomic_reactor.plugin - DEBUG - running plugin 'bump_release'
2015-10-07 04:56:02,769 - atomic_reactor.plugin - INFO - running plugin instance with args: '{u'author_email': u'build@example.com', u'git_ref': u'private-osbs-demo', u'push_url': u
'ssh://...', u'author_name': u'Build System'}'
2015-10-07 04:56:02,770 - atomic_reactor.plugins.bump_release - DEBUG - executing command: [u'/usr/bin/git', u'rev-parse', 'private-osbs-demo']
2015-10-07 04:56:02,780 - atomic_reactor.plugins.bump_release - DEBUG - git output: u'cc0e568f16f1d1c1a1780dc2b0db964fbc17ad80'
2015-10-07 04:56:02,781 - atomic_reactor.plugins.bump_release - DEBUG - executing command: [u'/usr/bin/git', u'rev-parse', u'HEAD']
2015-10-07 04:56:02,786 - atomic_reactor.plugins.bump_release - DEBUG - git output: u'cc0e568f16f1d1c1a1780dc2b0db964fbc17ad80'
2015-10-07 04:56:02,786 - atomic_reactor.plugins.bump_release - DEBUG - executing command: [u'/usr/bin/git', u'config', u'--get', u'branch.private-osbs-demo.remote']
2015-10-07 04:56:02,791 - atomic_reactor.plugins.bump_release - DEBUG - git output: u'origin'
2015-10-07 04:56:02,791 - atomic_reactor.plugins.bump_release - DEBUG - executing command: [u'/usr/bin/git', u'rev-parse', u'origin/private-osbs-demo']
2015-10-07 04:56:02,795 - atomic_reactor.plugins.bump_release - DEBUG - git output: u'cc0e568f16f1d1c1a1780dc2b0db964fbc17ad80'
2015-10-07 04:56:02,795 - atomic_reactor.plugins.bump_release - INFO - Verifying branch is at specified commit
2015-10-07 04:56:02,795 - atomic_reactor.plugins.bump_release - ERROR - Branch 'private-osbs-demo' is at commit cc0e568f16f1d1c1a1780dc2b0db964fbc17ad80 (expected private-osbs-demo)
2015-10-07 04:56:02,798 - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.5.1-py2.7.egg/atomic_reactor/plugin.py", line 203, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.5.1-py2.7.egg/atomic_reactor/plugins/pre_bump_release.py", line 306, in run
    self.verify_branch(branch, branch_sha)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.5.1-py2.7.egg/atomic_reactor/plugins/pre_bump_release.py", line 260, in verify_branch
    raise RuntimeError("Not at expected commit")
RuntimeError: Not at expected commit
```

**Comment by TomasTomecek** [comment]
This is a problem in configuration, not in code. I should have specify hash, not branch name. Should we validate this?

**Comment by twaugh** [comment]
We should try, yes. I guess we could validate that what we expect to be a hash is `all(ch for ch in string.hexdigits for ch in hash)`.

**Comment by TomasTomecek** [comment]
Since we clone the repo in osbs-client, I think we should be able to query git for hash provided. I just tried to find such command but unfortunately, since a branch in git is just a commit with a name, all of them are pretty much useless. E.g. `git cat-file -t $sha`.

The only suitable solution was:
```bash
$ git rev-list $branch | grep $sha
```

Other than that, I think your solution is way more practical. I would extend it to:

```python
all(ch in string.hexdigits for ch in hash) and len(hash) == 40
```

**Comment by twaugh** [comment]
Closing as this is an osbs-client issue.
