### ISSUE TITLE
timeout on removing image

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#347]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor/plugin.py", line 203, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor/plugins/exit_remove_built_image.py", line 40, in run
    self.tasker.remove_image(image, force=True)
  File "/usr/lib/python2.7/site-packages/atomic_reactor/core.py", line 492, in remove_image
    self.d.remove_image(image_id, force=force, noprune=noprune)  # returns None
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 788, in remove_image
    res = self._delete(self._url("/images/" + image), params=params)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 85, in _delete
    return self.delete(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 529, in delete
    return self.request('DELETE', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 422, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

this should *not* fail a build

**Comment by twaugh** [comment]
Was this the only failure? I've added an explicit test case for this but it passes: https://github.com/projectatomic/atomic-reactor/compare/master...347-remove-failure-nonfatal

**Comment by TomasTomecek** [comment]
The thing is that the image had ~1 gig and since the docker storage is on remote array, it took docker really long to actually remove the image. 

Not sure if the proper solution here is to just increase timeout.

**Comment by twaugh** [comment]
But even if an exit plugin falis, the build is not counted as a failure. See the test case.

**Comment by TomasTomecek** [comment]
You are right Tim. I realized that the tback didn't fail the build after I created this issue.

How about we increase the timeout to 120?
