### ISSUE TITLE
push_tarball_to_pulp traceback

### ISSUE THREAD

**Issue by twaugh** [projectatomic/atomic-reactor#387]
```
2015-11-20 12:30:55,439 - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.6.0-py2.7.egg/atomic_reactor/plugin.py", line 203, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.6.0-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py", line 237, in run
    image_names)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.6.0-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py", line 224, in push_tar
    return uploader.push_tarball_to_pulp(image_names)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.6.0-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py", line 153, in push_tarball_to_pulp
    ", ".join(map(str, task_ids)))
TypeError: argument 2 to map() must support iteration
```

**Comment by twaugh** [comment]
This was with dockpulp from release-engineering/dockpulp:master (29623c2).

**Comment by twaugh** [comment]
Works fine when merging https://github.com/projectatomic/atomic-reactor/pull/367.

**Comment by mmilata** [comment]
#367 is merged and from brief look at code it looks that `task_ids` is the return value of `Pulp.crane` which always returns list so this shouldn't happen. Please reopen if it does.
