### ISSUE TITLE
Race condition when running two builds with the same registry, image name and tag

### ISSUE THREAD

**Issue by mmilata** [projectatomic/atomic-reactor#67]
Running two same builds results in
```
2015-04-01 04:13:30,841 - dock.build - INFO - push built image to registry
2015-04-01 04:13:30,841 - dock.core - INFO - tag and push image
2015-04-01 04:13:30,841 - dock.core - DEBUG - image = 'user/image', target_image_name = 'user/image', reg_uri = 'registry.example.org', tag = ''
2015-04-01 04:13:30,841 - dock.core - INFO - tag image
2015-04-01 04:13:30,841 - dock.core - DEBUG - image = 'user/image', target_image_name = 'user/image', reg_uri = 'registry.example.org', tag = ''
Traceback (most recent call last):
  File "/usr/bin/dock", line 9, in <module>
    load_entry_point('dock==1.1.1', 'console_scripts', 'dock')()
  File "/usr/lib/python2.7/site-packages/dock/cli/main.py", line 187, in run
    cli.run()
  File "/usr/lib/python2.7/site-packages/dock/cli/main.py", line 170, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/dock/cli/main.py", line 66, in cli_inside_build
    build_inside(input=args.input, input_args=args.input_arg, substitutions=args.substitute)
  File "/usr/lib/python2.7/site-packages/dock/inner.py", line 215, in build_inside
    image = dbw.build_docker_image()
  File "/usr/lib/python2.7/site-packages/dock/inner.py", line 152, in build_docker_image
    self.builder.push_built_image(target_registry, insecure=self.target_registries_insecure)
  File "/usr/lib/python2.7/site-packages/dock/build.py", line 159, in push_built_image
    response = self.tasker.tag_and_push_image(self.image, local_registry, registry, tag=self.tag, insecure=insecure)
  File "/usr/lib/python2.7/site-packages/dock/core.py", line 394, in tag_and_push_image
    final_tag = self.tag_image(image, target_image_name, reg_uri=reg_uri, tag=tag)
  File "/usr/lib/python2.7/site-packages/dock/core.py", line 355, in tag_image
    response = self.d.tag(image, repository, tag=tag, force=force)  # returns True/False
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 897, in tag
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 95, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict: Tag latest is already set to image 38b331ae434a3490e76ab6d10979a53ffb8ef003991d39fb253c2dbcb1bd2f59, if you want to replace it, please use -f option")
```

I suppose what happened is that build1 tagged the image and build2 tried to tag the image with the same tag before build1 deleted the tag.

I'm not sure what the expected behavior should be - if we force-tag in the second build then one of the builds will fail because it will try to delete nonexistent tag. We'd have to make the tag & push sequence atomic somehow ...

Found by @goern.

**Comment by goern** [comment]
maybe prefix the image name with the build id? so that concurrent builds dont collide and let have each build job upload the image to the registry... so that the faster wins and makes the result a little more unpredictable but working aka producing images in a registry

**Comment by TomasTomecek** [comment]
You can explicitely ask for `latest` tag, then it won't fail (but one of your images will be lost, pretty much).

With prod strategy we are constructing image names that we put timestamps inside:
```python
timestamp = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
image = "%s/%s:%s-%s" % (self.user, self.component, self.koji_target, timestamp)
```

Maybe we could solve this by applying unique tag, e.g. `":ttomecek-20150402-133759357"` (and then tag it according to user request -- and if that fails, we will inform user and offer our tag).

**Comment by TomasTomecek** [comment]
this is already solved in whole osbs combo
